CREATE TABLE [dbo].[TAP8_DSGR_SCREEN] (
    [CD_SCREEN]      INT            IDENTITY (1, 1) NOT NULL,
    [CD_NAME]        VARCHAR (64)   NOT NULL,
    [DS_JSON]        TEXT           NOT NULL,
    [CD_INITBUTTON]  INT            NULL,
    [DS_CONFIG]      VARCHAR (1024) NULL,
    [CD_PROCESO]     VARCHAR (20)   NULL,
    [SN_SINCRONIZAR] VARCHAR (2)    CONSTRAINT [DF_TAP8_DSGR_SCREEN_SN_SINCRONIZAR] DEFAULT ('SI') NULL,
    [CD_PROYECTO]    VARCHAR (10)   NULL,
    [DS_DESCRIPCION] VARCHAR (1024) NULL,
    PRIMARY KEY CLUSTERED ([CD_SCREEN] ASC)
);

