CREATE TABLE [dbo].[TAP8_NAV_PARAM] (
    [CDPARAM]     VARCHAR (50)  NOT NULL,
    [DSVALUE]     VARCHAR (512) NOT NULL,
    [CD_PROYECTO] VARCHAR (10)  NULL,
    PRIMARY KEY CLUSTERED ([CDPARAM] ASC)
);

