CREATE TABLE [dbo].[TAP8_DSGR_FIELD] (
    [CD_FIELD]            INT            NOT NULL,
    [DS_NAME]             VARCHAR (64)   NOT NULL,
    [DS_LABEL]            VARCHAR (64)   NULL,
    [DS_TYPE]             VARCHAR (16)   NOT NULL,
    [DS_DEPENDFIELDNAMES] VARCHAR (128)  NULL,
    [DS_SCRIPT]           VARCHAR (1024) NULL,
    [DS_CONFIG]           VARCHAR (1024) NOT NULL,
    [CD_PROCESO]          VARCHAR (20)   NULL,
    [SN_SINCRONIZAR]      VARCHAR (2)    CONSTRAINT [DF_TAP8_DSGR_FIELD_SN_SINCRONIZAR] DEFAULT ('SI') NULL,
    [CD_PROYECTO]         VARCHAR (10)   NULL,
    PRIMARY KEY CLUSTERED ([CD_FIELD] ASC)
);

