CREATE TABLE [dbo].[TAP8_NAV_NAVIGATOR] (
    [CDNAVIGATOR]    INT            NOT NULL,
    [CDNAME]         VARCHAR (128)  NULL,
    [DSCONFIG]       VARCHAR (2048) NULL,
    [DSNODECONFIG]   VARCHAR (3072) NULL,
    [CD_PROCESO]     VARCHAR (20)   NULL,
    [SN_SINCRONIZAR] VARCHAR (2)    NULL,
    [DSCOLMODSCRIPT] VARCHAR (3072) NULL,
    [CD_PROYECTO]    VARCHAR (10)   NULL
);

