CREATE TABLE [dbo].[TAP8_GRIDS_GRIDSET] (
    [CD_GRIDSET]     INT            NOT NULL,
    [CD_NAME]        VARCHAR (64)   NOT NULL,
    [DS_TITLE]       VARCHAR (128)  NOT NULL,
    [DS_MENUTYPE]    VARCHAR (32)   NULL,
    [DS_CONFIG]      VARCHAR (1024) NULL,
    [DS_MENUCONFIG]  VARCHAR (1024) NULL,
    [CD_PROCESO]     VARCHAR (20)   NULL,
    [SN_SINCRONIZAR] VARCHAR (2)    CONSTRAINT [DF_TAP8_GRIDS_GRIDSET_SN_SINCRONIZAR] DEFAULT ('SI') NULL,
    [CD_PROYECTO]    VARCHAR (10)   NULL,
    PRIMARY KEY CLUSTERED ([CD_GRIDSET] ASC)
);

