CREATE TABLE [dbo].[TAP8_WFM_QUERY_COLUMNS] (
    [CD_QUERY]       INT          NOT NULL,
    [CD_COLUMN]      INT          NOT NULL,
    [CD_PROCESO]     VARCHAR (20) NULL,
    [SN_SINCRONIZAR] VARCHAR (2)  CONSTRAINT [DF_TAP8_WFM_QUERY_COLUMNS_SN_SINCRONIZAR] DEFAULT ('SI') NULL,
    [CD_PROYECTO]    VARCHAR (10) NULL,
    PRIMARY KEY CLUSTERED ([CD_QUERY] ASC, [CD_COLUMN] ASC),
    FOREIGN KEY ([CD_COLUMN]) REFERENCES [dbo].[TAP8_WFM_COLUMN] ([CD_COLUMN]),
    FOREIGN KEY ([CD_QUERY]) REFERENCES [dbo].[TAP8_WFM_QUERY] ([CD_QUERY])
);

