CREATE TABLE [dbo].[TAP8_GRIDS_GRIDSET_GRIDS] (
    [CD_GRIDSET]     INT          NOT NULL,
    [CD_GRID]        INT          NOT NULL,
    [CD_PROCESO]     VARCHAR (20) NULL,
    [SN_SINCRONIZAR] VARCHAR (2)  CONSTRAINT [DF_TAP8_GRIDS_GRIDSET_GRIDS_SN_SINCRONIZAR] DEFAULT ('SI') NULL,
    [CD_PROYECTO]    VARCHAR (10) NULL,
    PRIMARY KEY CLUSTERED ([CD_GRIDSET] ASC, [CD_GRID] ASC),
    FOREIGN KEY ([CD_GRID]) REFERENCES [dbo].[TAP8_GRIDS_GRID] ([CD_GRID]),
    FOREIGN KEY ([CD_GRIDSET]) REFERENCES [dbo].[TAP8_GRIDS_GRIDSET] ([CD_GRIDSET])
);

