CREATE TABLE [dbo].[TAP8_WFM_DATASOURCE] (
    [CD_DATASOURCE]  INT            NOT NULL,
    [CD_NAME]        VARCHAR (100)  NOT NULL,
    [CD_OWNER]       VARCHAR (50)   NOT NULL,
    [CD_CONTEXT]     INT            NOT NULL,
    [DS_CONFIG]      VARCHAR (3072) NULL,
    [DS_DESCRIPTION] VARCHAR (200)  NOT NULL,
    [CD_PROCESO]     VARCHAR (20)   NULL,
    [SN_SINCRONIZAR] VARCHAR (2)    CONSTRAINT [DF_TAP8_WFM_DATASOURCE_SN_SINCRONIZAR] DEFAULT ('SI') NULL,
    [CD_PROYECTO]    VARCHAR (10)   NULL,
    PRIMARY KEY CLUSTERED ([CD_DATASOURCE] ASC)
);

