CREATE TABLE [dbo].[TAP8_WFM_COLUMN] (
    [CD_COLUMN]      INT            NOT NULL,
    [CD_NAME]        VARCHAR (100)  NOT NULL,
    [CD_DATA_TYPE]   VARCHAR (20)   NOT NULL,
    [DS_DESCRIPTION] VARCHAR (200)  NOT NULL,
    [DS_CONFIG]      VARCHAR (3072) NULL,
    [CD_PROCESO]     VARCHAR (20)   NULL,
    [SN_SINCRONIZAR] VARCHAR (2)    CONSTRAINT [DF_TAP8_WFM_COLUMN_SN_SINCRONIZAR] DEFAULT ('SI') NULL,
    [CD_PROYECTO]    VARCHAR (10)   NULL,
    PRIMARY KEY CLUSTERED ([CD_COLUMN] ASC),
    CHECK ([CD_DATA_TYPE]='BOOLEAN' OR [CD_DATA_TYPE]='DATE' OR [CD_DATA_TYPE]='REAL' OR [CD_DATA_TYPE]='INTEGER' OR [CD_DATA_TYPE]='STRING')
);

