CREATE TABLE [dbo].[TAP8_WFM_QUERY] (
    [CD_QUERY]       INT            NOT NULL,
    [CD_NAME]        VARCHAR (100)  NOT NULL,
    [DS_SQL]         VARCHAR (1024) NULL,
    [DS_PREFS]       VARCHAR (3072) NULL,
    [DS_CONFIG]      VARCHAR (3072) NULL,
    [DS_DESCRIPTION] VARCHAR (200)  NOT NULL,
    [CD_PROCESO]     VARCHAR (20)   NULL,
    [SN_SINCRONIZAR] VARCHAR (2)    CONSTRAINT [DF_TAP8_WFM_QUERY_SN_SINCRONIZAR] DEFAULT ('SI') NULL,
    [CD_PROYECTO]    VARCHAR (10)   NULL,
    PRIMARY KEY CLUSTERED ([CD_QUERY] ASC)
);

