CREATE TABLE [dbo].[TAP8_WFM_PARAM] (
    [CD_PARAM]       VARCHAR (50)  NOT NULL,
    [DS_VALUE]       VARCHAR (512) NOT NULL,
    [CD_PROCESO]     VARCHAR (20)  NULL,
    [SN_SINCRONIZAR] VARCHAR (2)   NULL,
    [CD_PROYECTO]    VARCHAR (10)  NULL,
    PRIMARY KEY CLUSTERED ([CD_PARAM] ASC)
);

