CREATE TABLE [dbo].[TAP8_WFM_QUERY_GRIDSETS] (
    [CD_QUERY]       INT          NOT NULL,
    [CD_GRIDSET]     INT          NOT NULL,
    [CD_PROCESO]     VARCHAR (20) NULL,
    [SN_SINCRONIZAR] VARCHAR (2)  CONSTRAINT [DF_TAP8_WFM_QUERY_GRIDSETS_SN_SINCRONIZAR] DEFAULT ('SI') NULL,
    [CD_PROYECTO]    VARCHAR (10) NULL,
    PRIMARY KEY CLUSTERED ([CD_QUERY] ASC, [CD_GRIDSET] ASC),
    FOREIGN KEY ([CD_GRIDSET]) REFERENCES [dbo].[TAP8_GRIDS_GRIDSET] ([CD_GRIDSET]),
    FOREIGN KEY ([CD_QUERY]) REFERENCES [dbo].[TAP8_WFM_QUERY] ([CD_QUERY])
);

