CREATE TABLE [dbo].[TAP8_NAV_QUERY_old] (
    [CDQUERY]        INT            IDENTITY (1, 1) NOT NULL,
    [CDNAME]         VARCHAR (128)  NULL,
    [CDNAVYNAME]     VARCHAR (128)  NULL,
    [DSOBJSTORES]    VARCHAR (128)  NULL,
    [DSCESQL]        VARCHAR (512)  NULL,
    [DSQUEUENAME]    VARCHAR (128)  NULL,
    [DSPESQL]        VARCHAR (512)  NULL,
    [DSPATHS]        VARCHAR (128)  NULL,
    [DSUSERS]        VARCHAR (128)  NULL,
    [DSCONFIG]       VARCHAR (2048) NULL,
    [DSSCRIPT]       VARCHAR (3072) NULL,
    [CD_PROCESO]     VARCHAR (20)   NULL,
    [SN_SINCRONIZAR] VARCHAR (2)    CONSTRAINT [DF_TAP8_NAV_QUERY_SN_SINCRONIZAR] DEFAULT ('SI') NULL,
    [DSCOLMODSCRIPT] VARCHAR (3072) NULL,
    [CD_PROYECTO]    VARCHAR (10)   NULL,
    PRIMARY KEY CLUSTERED ([CDQUERY] ASC)
);

