CREATE TABLE [dbo].[TAP8_WFM_DATASOURCE_QUERY] (
    [CD_DATASOURCE]  INT          NOT NULL,
    [CD_QUERY]       INT          NOT NULL,
    [CD_PROCESO]     VARCHAR (20) NULL,
    [SN_SINCRONIZAR] VARCHAR (2)  CONSTRAINT [DF_TAP8_WFM_DATASOURCE_QUERY_SN_SINCRONIZAR] DEFAULT ('SI') NULL,
    [CD_PROYECTO]    VARCHAR (10) NULL,
    PRIMARY KEY CLUSTERED ([CD_DATASOURCE] ASC, [CD_QUERY] ASC),
    FOREIGN KEY ([CD_DATASOURCE]) REFERENCES [dbo].[TAP8_WFM_DATASOURCE] ([CD_DATASOURCE]),
    FOREIGN KEY ([CD_QUERY]) REFERENCES [dbo].[TAP8_WFM_QUERY] ([CD_QUERY])
);

