CREATE TABLE [dbo].[TAP8_WFM_CONTEXT] (
    [CD_CONTEXT]      INT            NOT NULL,
    [CD_CONTEXT_CODE] VARCHAR (50)   NOT NULL,
    [DS_DESCRIPTION]  VARCHAR (200)  NOT NULL,
    [DS_CONFIG]       VARCHAR (3072) NULL,
    [CD_PROCESO]      VARCHAR (20)   NULL,
    [SN_SINCRONIZAR]  VARCHAR (2)    CONSTRAINT [DF_TAP8_WFM_CONTEXT_SN_SINCRONIZAR] DEFAULT ('SI') NULL,
    [CD_PROYECTO]     VARCHAR (10)   NULL,
    PRIMARY KEY CLUSTERED ([CD_CONTEXT] ASC)
);

