CREATE  PROCEDURE [dbo].[cnf_sp_Lista_Navy] (
@IdProyecto				varchar(20) out
)

as

SELECT CDNAVIGATOR, CDNAME, DSCONFIG + ' ' as DSCONFIG, DSNODECONFIG + ' ' as DSNODECONFIG , DSCOLMODSCRIPT + ' ' as DSCOLMODSCRIPT
FROM TAP8_NAV_NAVIGATOR
WHERE CD_PROYECTO LIKE @IdProyecto
