CREATE  PROCEDURE [dbo].[cnf_sp_Eliminar_Boton] (
@CD_BUTTON			int out
)

as

DELETE FROM TAP8_WFM_QUERY_BUTTONS WHERE CD_BUTTON = @CD_BUTTON

DELETE FROM TAP8_WFM_BUTTON WHERE CD_BUTTON = @CD_BUTTON
DELETE FROM TAP8_WFM_BUTTON WHERE CD_BUTTON = @CD_BUTTON



