
CREATE PROCEDURE [dbo].[UTIL_GETINSPECTORCOMPONENTS]

@NOMBRESP VARCHAR(MAX) 

AS

DECLARE @BUTTON_NAME VARCHAR(20) =''
DECLARE @FIELD_NAME VARCHAR(20) =''
DECLARE @GRID_NAME VARCHAR(20) =''

DECLARE CURSOR_BUTTON CURSOR 
FOR SELECT CD_NAME FROM [dbo].[TAP8_WFM_BUTTON]
WHERE  CD_PROYECTO = 'CARTERO' AND DS_SCRIPT LIKE '%'+@NOMBRESP+'%'

DECLARE CURSOR_FIELD CURSOR
FOR SELECT DS_NAME FROM [dbo].[TAP8_DSGR_FIELD]
WHERE  CD_PROYECTO = 'CARTERO' AND DS_SCRIPT LIKE '%'+@NOMBRESP+'%'

DECLARE CURSOR_GRID CURSOR
FOR SELECT CD_NAME FROM [dbo].[TAP8_GRIDS_GRID]
WHERE  CD_PROYECTO = 'CARTERO' AND DS_DATASCRIPT LIKE '%'+@NOMBRESP+'%'


OPEN CURSOR_BUTTON

FETCH CURSOR_BUTTON INTO @BUTTON_NAME

PRINT ''
PRINT 'BOTONES'
PRINT '-------------------------'

WHILE(@@FETCH_STATUS = 0) 
BEGIN 

FETCH CURSOR_BUTTON INTO @BUTTON_NAME

PRINT @BUTTON_NAME

END

CLOSE CURSOR_BUTTON
DEALLOCATE CURSOR_BUTTON

-- *********************************************************

OPEN CURSOR_FIELD

FETCH CURSOR_FIELD INTO @FIELD_NAME

PRINT ''
PRINT 'FIELDS'
PRINT '-------------------------'

WHILE(@@FETCH_STATUS = 0) 
BEGIN 

FETCH CURSOR_FIELD INTO @FIELD_NAME

PRINT @FIELD_NAME

END

CLOSE CURSOR_FIELD
DEALLOCATE CURSOR_FIELD

-- *******************************************************

OPEN CURSOR_GRID

FETCH CURSOR_GRID INTO @GRID_NAME

PRINT ''
PRINT 'GRIDS'
PRINT '-------------------------'

WHILE(@@FETCH_STATUS = 0) 
BEGIN 

FETCH CURSOR_GRID INTO @GRID_NAME

PRINT @GRID_NAME

END

CLOSE CURSOR_GRID
DEALLOCATE CURSOR_GRID





